package eu.andymel.msgcontainer.path;
public enum TestMilestones {

	CREATION,
	BEFORE_HANDLER_CONTEXT,
		BEFORE_SEARCH_HANDLER,
		AFTER_SEARCH_HANDLER,
		BEFORE_HANDLER,
			BEFORE_DAO_GETSTATE,
				BEFORE_DBPOOL,
				AFTER_DBPOOL,
				BEFORE_DB_GETSTATE,
				AFTER_DB_GETSTATE,
				BEFORE_DB_GETSTATE_RESULTSET,
				AFTER_DB_GETSTATE_RESULTSET,
			AFTER_DAO_GETSTATE,
			
			BEFORE_CALC1,
			AFTER_CALC1,
			
			BEFORE_DECIDER,
			AFTER_DECIDER,
			
			BEFORE_DAO_SAVE,
				BEFORE_DB_SAVE_DESICION1,
				AFTER_DB_SAVE_DESICION1,
				BEFORE_DB_SAVE_DECISION1_RESULTSET,
				AFTER_DB_SAVE_DECISION1_RESULTSET,
				BEFORE_DB_SAVE_DESICION2,
				AFTER_DB_SAVE_DESICION2,
				BEFORE_DB_SAVE_DECISION2_RESULTSET,
				AFTER_DB_SAVE_DECISION2_RESULTSET,
			AFTER_DAO_SAVE,
		AFTER_HANDLER,
	AFTER_HANDLER_CONTEXT;
	
}
